version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "poetry run python src/app/main.py"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres